# Generated by Django 5.1.2 on 2024-10-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('revenue', models.FloatField(default=0)),
                ('budget', models.FloatField(default=0)),
                ('runtime', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('original_language', models.CharField(max_length=50)),
                ('production_company_id', models.PositiveIntegerField()),
                ('genre_id', models.PositiveIntegerField()),
                ('languages', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True)),
            ],
        ),
    ]
